//recevoir tous les utilisateurs 
GET http://localhost:3000/utilisateurs/

###
//recevoir un utilisateur à l'aide de son ID passé comme pamarmètre de l'URL
GET http://localhost:3000/utilisateurs/612a4bd5d30aad0528706371

###
//créer un utilisateur avec le body passé 

POST http://localhost:3000/utilisateurs
Content-Type: application/json

{
    "name":"mar",
    "email":"ma@yah.com",
    "tel":"23739230",
    "profession":"agriculateur",
    "region":"nord",
    "address":"beja",
    "subscriber":"false",
    "password":"aze123"
}

###

//effecer un utilisateur à l'aide de son ID passé comme pamarmètre de l'URL
DELETE https://localhost:3000/utilisateurs/5e90dfcf29a06931b8639bae

###
//màj un utilisateur à l'aide de son ID passé comme pamarmètre de l'URL et des paramètres passées en body
PATCH  http://localhost:3000/utilisateurs/5eb81e723f9b87151c583569
Content-Type: application/json

{
    "password":"marwennn"
}
###
PATCH  http://localhost:3000/utilisateurs/612a4bd5d30aad0528706371
Content-Type: application/json

{
    "subscriber":"true"
}
###
//verifier les donées insérées et retourner un token lors du login
POST http://localhost:3000/login
Content-Type: application/json

{
    "email":"mar@yahoo.com",
    "password":"aze123"
}
###
//envoyer les plantes associées de l'utilisateurs avec token inséré en Authorization Header 
GET http://localhost:3000/plantes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcm9vb0BnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCR3S3dxZjVEa0ZTYUlLUVY2NFpJVnhPNzZ4OFJRR0lIVmlqNTB1ZElOaHVGQUsvQVBLWFhZLiIsIm5hbWUiOiJtYXJvIiwiaWF0IjoxNTg2ODE2MjU4fQ.JXLGUHgrSyDUuIbBBywsdBqjfiZXujzusveeQEN6098

###